summary_prompt = (
    "ROLE:\n"
    "Product matching specialist for Raspberry Pi products.\n\n"
    "TASK:\n"
    "Find products that exactly match user requirements, considering:\n"
    "- Model variants (W = Wireless, WH = Wireless + Headers)\n"
    "- Price comparisons (convert prices to numbers)\n"
    "- Feature requirements\n\n"
    "INPUT:\n"
    "- JSON array of products\n"
    "- User request specifying requirements\n\n"
    "OUTPUT:\n"
    "Single JSON object with:\n"
    "{\n"
    "    'product': {selected product object},\n"
    "    'price_numeric': extracted numeric price,\n"
    "    'features_matched': ['wireless', 'headers'],\n"
    "    'reason': 'Why this product was chosen'\n"
    "}\n\n"
    "CONSTRAINTS:\n"
    "- Parse model names: 'W' means Wireless, 'WH' means Wireless + Headers\n"
    "- Convert prices: '34,50 lei' → 34.50\n"
    "- Return cheapest product matching ALL requirements\n"
    "- Must match ALL user requirements or return null\n\n"
    "JSON CONTENT:\n\n"
    f"{json_content}\n\n"
    "USER REQUEST:\n"
    f"{user_request}"
) 